// AUTO-GENERATED from h7-nodality/upload/lang.js aktivity.levelDetails.
// Do not edit by hand — keep in sync by re-running the generator.

export interface LevelActivityDetail {
  name: string;
  subtitle: string;
  desc: string;
}

export interface LevelInfo {
  subtitle: string;
  description: string;
  activities: LevelActivityDetail[];
}

export type LevelKey = "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "h7";
export type LevelActivityDetails = Record<LevelKey, LevelInfo>;

const CS_DETAILS: LevelActivityDetails = {
  h1: {
    subtitle: "Startovací schod",
    description: "Cílem je probudit tělo a vytvořit základní návyk.",
    activities: [
      { name: "Chůze", subtitle: "Rychlá chůze (4–6 km/h)", desc: "Jděte tempem, jako byste spěchali na důležitou schůzku. Vaše dýchání se musí zrychlit natolik, že sice zvládnete mluvit, ale už byste nedokázali plynule zpívat." },
      { name: "Pohyb H7", subtitle: "Univerzální aktivita", desc: "Pro všechny nečekané momenty dne, kdy se citelně zadýcháte (dobíhání dopravy, rychlý přesun městem), ale aktivita nemá specifický název." },
      { name: "Cvičení", subtitle: "Aktivní home office přestávky", desc: "Místo kávy zařaďte 9 minut dřepů, kliků o stůl nebo dynamického protahování. Tento krátký blok stačí k okysličení mozku a aktivaci srdce." },
      { name: "Schody", subtitle: "Chůze do schodů", desc: "Využijte schodiště jako osobní trenažér. Jděte plynulým tempem bez zastavování a soustřeďte se na hluboký výdech při každém kroku." },
      { name: "Zahrada", subtitle: "Zahradní práce střední zátěže", desc: "Hrabání listí, sázení nebo úprava záhonů. Počítá se, pokud jste v neustálém pohybu, zapojujete svaly a cítíte mírné zadýchání." },
      { name: "Hra", subtitle: "Hravý pohyb s dětmi nebo mazlíčky", desc: "Intenzivní hra na honěnou, zápasení na koberci nebo aktivní házení míčku. Aktivujete srdce přirozeně skrze emoce, aniž byste vnímali námahu." },
      { name: "Turistika", subtitle: "Pěší turistika v mírně zvlněném terénu", desc: "Stoupání přirozeně nutí plíce k hlubší práci. Udržujte svižné tempo a vnímejte aktivaci stabilizačních svalů." },
      { name: "Cyklistika", subtitle: "Rekreační jízda na rovině", desc: "Soustřeďte se na plynulé šlapání bez dlouhých přestávek. Aktivita splňuje H1 ve chvíli, kdy cítíte, že dech je rytmický a hlubší než v klidu." },
      { name: "Úklid", subtitle: "Dynamický domácí úklid", desc: "Vysávání, vytírání podlahy nebo mytí oken prováděné v energickém tempu. Zapojujte široké pohyby paží, aby se srdce rozpracovalo." },
      { name: "Trenažér", subtitle: "Elliptical / Orbitrek", desc: "Ideální pro začátečníky díky eliminaci nárazů na klouby. Nastavte mírný odpor a udržujte tempo, při kterém zvládáte jen krátkou konverzaci." },
      { name: "Nordic Walking", subtitle: "Chůze s holemi", desc: "Správná technika zapojí až 90 % svalů. Aktivní odpich vám pomůže přirozeně zrychlit krok a prohloubit dýchání." },
      { name: "Plavání", subtitle: "Základní plavání a technika", desc: "Soustřeďte se na plynulý pohyb a výdech do vody. Stačí udržet konstantní tempo, při kterém cítíte jemný odpor vody a zvýšený tep." },
      { name: "Vodní chůze", subtitle: "Aquawalking v bazénu s vodou po pás", desc: "Odpor vody zvyšuje náročnost každého kroku. Snadná a bezpečná metoda pro aktivaci srdce i při zdánlivě pomalém pohybu." },
      { name: "Jóga", subtitle: "Aktivní a dynamické formy (např. Vinyasa)", desc: "Započítává se pouze tehdy, pokud je tempo takové, že cítíte nárůst vnitřního tepla a dechová frekvence se hmatatelně zvýší." },
      { name: "Koloběžka", subtitle: "Rekreační jízda na koloběžce", desc: "Pravidelně střídejte odrazovou nohu a udržujte tempo, které vás nutí k hlubšímu dýchání. Nepočítejte pasivní sjíždění svahů." },
      { name: "Tanec", subtitle: "Společenský nebo domácí tanec", desc: "Pohyb musí zapojit celé tělo včetně paží. Tančete tak intenzivně, abyste se po každé skladbě cítili příjemně zadýchaní." },
      { name: "Cyklistika", subtitle: "Trenažér / Stacionární kolo", desc: "Jízda v aerobním pásmu s plynulou rotací proti mírnému odporu. Udržujte úsilí, u kterého se lehce zapotíte." },
      { name: "Golf", subtitle: "Hra s nošením bagu", desc: "Započítávejte pouze minuty ostré chůze mezi jamkami s vybavením na zádech. Zátěž bagu je faktorem, který aktivuje srdce do úrovně H1." },
      { name: "Tai-chi", subtitle: "Dynamické provedení", desc: "Musí být prováděno v hlubších postojích s vědomým silovým zapojením celého těla, které vede k vnitřnímu zahřátí a prohloubení dechu." },
    ],
  },
  h2: {
    subtitle: "Stabilizační schod",
    description: "Budování návyku. Pohyb se stává součástí vaší identity.",
    activities: [
      { name: "Posilování", subtitle: "Cvičení s vlastní vahou", desc: "Základní cviky jako dřepy, plank nebo výpady v kontrolovaném tempu. Počítejte pouze čistý čas cvičení se svalovým napětím a zrychleným tepem." },
      { name: "Cyklistika", subtitle: "Silniční a zpevněné cesty", desc: "Plynulé tempo na rovině či v mírném terénu (výletní konverzační úsilí). Cítíte práci stehen a dech je hluboký, ale stále můžete mluvit." },
      { name: "Doprava", subtitle: "Aktivní dojíždění (kolo/koloběžka)", desc: "Využijte cestu do práce jako tréninkový blok. Nejefektivnější způsob, jak do dne vložit pohyb, který vás přirozeně zadýchá." },
      { name: "Zahrada", subtitle: "Těžké zahradní práce", desc: "Rytí, přehazování kompostu nebo vození naložených koleček. Počítejte minuty, kdy jste v neustálém pohybu a cítíte nárok na své plíce." },
      { name: "Běh", subtitle: "Indiánský běh", desc: "Střídání 1 minuty lehkého klusu a 2 minut chůze. Šetří klouby a umožňuje srdci plynule si zvykat na vyšší zátěž. Postupně dobu běhu prodlužujte." },
      { name: "Chůze", subtitle: "Power Walking v terénu", desc: "Mírné kopce, které přirozeně zvýší tep i bez běhu. Práce proti gravitaci je vynikající pro kardiovaskulární systém bez tvrdých dopadů." },
      { name: "Plavání", subtitle: "Různé styly s odpočinkem", desc: "Střídejte prsa, znak a kraul s krátkými pauzami. Klíčem je plynulost a výdech do vody, který zvyšuje nároky na plíce i při nižším tempu." },
      { name: "Pilates", subtitle: "Cvičení na střed těla", desc: "Soustřeďte se na kontrolu core a precizní dýchání. Svalové napětí musí vést k pocitu vnitřního horka a zrychlení srdečního tepu." },
      { name: "Badminton", subtitle: "Rekreační hra", desc: "I při hře na louce se při dobíhání košíčku a práci na špičkách slušně zapotíte. Udržujte hru v pohybu s minimem pauz." },
      { name: "Bruslení", subtitle: "In-line nebo led", desc: "Plynulý pohyb šetřící klouby, vyžadující zapojení stabilizačního systému. Na ledě sportujte, jen pokud pohyb ovládáte. Udržujte konverzační tempo." },
      { name: "Stolní tenis", subtitle: "Rekreační hra", desc: "Aktivní pohyb nohama a změny těžiště. Počítejte čas samotné hry v neustálém střehu, nikoliv sbírání míčků pod stolem." },
      { name: "Trénink psa", subtitle: "Dog Agility / Aktivní trénink", desc: "Běhání vedle psa přes překážky. Emoce pomáhají zapomenout na námahu, dech a tep jdou přirozeně nahoru." },
      { name: "Vodní cvičení", subtitle: "Aqua aerobik / Aqua-jogging", desc: "Využití odporu vody k posílení těla bez přetížení šlach. Běh po dně nebo s pásem spolehlivě udrží srdce v zóně zdravého pohybu." },
      { name: "Lyžování", subtitle: "Sjezdové lyžování", desc: "Počítejte pouze čisté minuty aktivního sjezdu, kdy svaly nohou pracují. Čas na lanovce nebo ve frontě je relaxace (H0)." },
      { name: "Běžky", subtitle: "Klasický styl", desc: "Upravená stopa a rovinatý terén pro 'výletní' tempo. Zapojení paží i nohou současně efektivně aktivuje celé tělo." },
      { name: "Trampolína", subtitle: "Mírné skoky a pohupování", desc: "Skvělý způsob pro rozproudění lymfy a posílení středu těla. Cítíte prohloubený dech a nástup endorfinů." },
      { name: "Míčové hry", subtitle: "Volejbal / Nohejbal", desc: "Započítávejte čistý čas setů v aktivním zapojení na špičkách. Hra musí mít spád pro trvalé mírné zvýšení dechové frekvence." },
      { name: "Trenažér", subtitle: "Stairstepper / Schodový trenažér", desc: "Tempo simulující klidný výstup do kopce. Ruce madla jen jistí. Cílem je konstantní, mírně zadýchávající rytmus." },
      { name: "Chůze", subtitle: "Plogging (chůze se sběrem odpadků)", desc: "Kombinace rychlé chůze s neustálými dřepy a předklony. Aktivuje metabolismus komplexněji než běžná chůze." },
      { name: "Veslování", subtitle: "Trenažér i voda", desc: "Stabilní tempo záběrů s důrazem na odraz nohou a plynulé dýchání. Hlídejte si, abyste zůstali v komfortní konverzační zóně." },
      { name: "Lezení", subtitle: "Bouldering pro začátečníky", desc: "Lehké cesty nutící k plynulému pohybu nahoru. Počítejte momenty lezení, kdy svalové napětí zvyšuje nároky na dech." },
      { name: "Košíková", subtitle: "Individuální střelba na koš", desc: "Aktivní střelba spojená s okamžitým dobíháním vlastních odrazů. Udrží srdce v aktivitě bez vyčerpání ze hry 3 na 3." },
      { name: "Vodní sporty", subtitle: "Kanoistika / SUP", desc: "Rytmické záběry pádlem na klidné vodě zapojující rotaci trupu. Ideální pro stabilitu a mírnou aktivaci dechu v přírodě." },
      { name: "Chůze", subtitle: "Sněžnice na rovině", desc: "Pohyb v hlubokém sněhu klade odpor a zvyšuje náročnost každého kroku. Umožňuje udržet plynulé tempo a prohloubený dech." },
      { name: "Pálkovací hry", subtitle: "Softball / Baseball", desc: "Počítejte pouze minuty aktivního běhu, nadhazování nebo pálkování. Většina času je statická, proto sčítejte jen momenty zrychleného tepu." },
    ],
  },
  h3: {
    subtitle: "Kondiční schod",
    description: "Pohyb už je radost. Zde začínáme budovat skutečnou kondici.",
    activities: [
      { name: "Cvičení", subtitle: "Aerobik / Zumba / Bodyform", desc: "Skupinové lekce, které vás díky hudbě a rytmu udrží v konstantním kondičním tempu. Nejdostupnější forma organizovaného cvičení." },
      { name: "Běh", subtitle: "Jogging / Pomalý běh", desc: "Základní kámen vytrvalosti s lehkým došlapem. Užíváte si pohyb krajinou a délku trasy navyšujete maximálně o 5–10 % týdně." },
      { name: "Kruhový trénink", subtitle: "Intenzivní střídání cviků", desc: "Na různé svalové partie s minimálními pauzami. Udrží tep v optimální kondiční zóně a efektivně buduje sílu i vytrvalost." },
      { name: "Míčové hry", subtitle: "Fotbal / Florbal / Basketbal", desc: "Rekreační zápasy na menším prostoru s intervalovým charakterem. Krátké sprinty a změny směru vás dostanou do zóny aktivního zadýchání." },
      { name: "Tenis", subtitle: "Rekreační úroveň", desc: "Aktivní hra na celém kurtu se soustředěním na pohyb nohou. Plynulé výměny udržují krevní oběh v neustálé aktivitě." },
      { name: "Cyklistika", subtitle: "Spinning / Cyklotrenažér", desc: "Intenzivní šlapání v kontrolovaném prostředí s hudbou či aplikacemi. Plné soustředění na výkon a dech bez vnějších vlivů." },
      { name: "Plavání", subtitle: "Kondiční plavání", desc: "Souvislé plavání několika bazénů v kuse se střídáním stylů (prsa, znak). Minimalizace pauz u břehu pro udržení tepu v kondiční zóně." },
      { name: "Jóga", subtitle: "Power jóga", desc: "Dynamické střídání pozic v souladu s dechem, kladoucí nároky na sílu a stabilitu. Dech musí být hluboký a vědomě zrychlený po celou dobu." },
      { name: "Cvičení", subtitle: "TRX / Kettlebell", desc: "Funkční trénink s odporem nářadí. Technická preciznost s krátkými odpočinkovými intervaly udrží srdce v aktivitě a svaly pod napětím." },
      { name: "Chůze", subtitle: "Rucking (chůze se zátěžovým batohem)", desc: "Svižná chůze s batohem (5–15 % tělesné hmotnosti). Efektivní budování kondice šetřící klouby, ale aktivující plíce jako jogging." },
      { name: "Turistika", subtitle: "Horská turistika (strmá)", desc: "Rychlejší chůze v členitém terénu s výrazným převýšením. Práce proti gravitaci spolehlivě zajistí vysokou tepovou frekvenci." },
      { name: "Tanec", subtitle: "Latino / Intenzivní lekce", desc: "Energické sestavy jako salsa, vyžadující rychlou práci nohou a trupu. Pohyb v rytmu vás udrží v zóně kondičního zadýchání." },
      { name: "Schody", subtitle: "Intenzivní trénink", desc: "Cílené vybíhání nebo velmi rychlá chůze do schodů (dva po dva). Nejrychlejší cesta k prověření vašeho 'motoru' a síly nohou." },
      { name: "Bojová umění", subtitle: "Judo / Karate – základní trénink", desc: "Nácvik technik v pohybu, stínový boj nebo lehký kondiční sparing. Výbušné pohyby spolehlivě aktivují kardiovaskulární systém." },
      { name: "Lyžování", subtitle: "Skialpinismus (lehký terén)", desc: "Stoupání do kopce na lyžích, zapojující celé tělo. Odpor sněhu a práce s holemi zajistí zónu prohloubeného kondičního dýchání." },
      { name: "Jízda", subtitle: "Skate / Longboard", desc: "Aktivní pohyb městem s častým odrazem. Počítejte čas, kdy se aktivně odrážíte nebo pracujete s těžištěm, nikoliv pasivní stání." },
      { name: "Tanec", subtitle: "Pole dance (kondiční)", desc: "Silově-akrobatické cvičení na tyči vyžadující zpevnění středu těla. Počítejte čas nácviku prvků, které vás donutí k hlubokému dýchání." },
      { name: "Plavání", subtitle: "Open water (přírodní plavání)", desc: "Souvislý pohyb ve volné vodě bez stěn. Náročnější na orientaci a udržení teploty, což dělá z plavání vynikající kondiční aktivitu." },
    ],
  },
  h4: {
    subtitle: "Udržitelný střed",
    description: "Zlatý standard H7. Zde se láme chleba pro celoživotní zdraví.",
    activities: [
      { name: "Cvičení", subtitle: "Tabata / HIIT", desc: "Vysoce intenzivní intervalový trénink pro maximální spalování. Střídání maximálního úsilí a krátkého odpočinku udrží metabolismus nastartovaný." },
      { name: "Běh", subtitle: "Systémový trénink", desc: "Střídání délky a intenzity (např. fartlek). Učíte tělo pracovat efektivně i při delší zátěži, kdy váš vnitřní diesel musí běžet naplno." },
      { name: "Tenis", subtitle: "Pravidelný trénink / Badminton", desc: "Zaměření na dril úderů a herní taktiku. Neustálý pohyb v kombinaci s technikou dělá z tréninku velmi intenzivní jednotku." },
      { name: "Cvičení", subtitle: "CrossFit", desc: "Kombinace gymnastiky, vzpírání a kardia. Soustředíte se na techniku a plynulost v rámci tréninku dne (WOD), což prověří sílu i vytrvalost." },
      { name: "Cyklistika", subtitle: "Horské kolo (MTB)", desc: "Jízda v terénu vyžaduje sílu i techniku. Každý kořen a stoupání jsou přirozeným intervalem pro nohy, trup i paže." },
      { name: "Běh", subtitle: "Trail Running", desc: "Běh mimo zpevněné cesty přes překážky. Vyžaduje mnohem více stability a síly než silniční běh. Výběhy v terénu budují robustní kondici." },
      { name: "Běh", subtitle: "Běh s kočárkem", desc: "Delší trasy se zátěží výrazně zvyšují náročnost na střed těla a paže. Spojení péče o dítě s kvalitním vytrvalostním tréninkem." },
      { name: "Veslování", subtitle: "Intenzivní trénink", desc: "Silný záběr nohama a plynulé dýchání. Komplexní nálož pro celé tělo budující svalovou vytrvalost a kapacitu plic bez nárazů." },
      { name: "Squash", subtitle: "Výbušný pohyb se změnami směru", desc: "Intervalový charakter hry je skvělý pro spalování tuků a posílení srdce. Díky tempu se do H4 dostanete velmi rychle." },
      { name: "Bojové sporty", subtitle: "Box / Kickbox (kondiční)", desc: "Práce na pytli nebo s lapy v explozivních sekvencích. Buduje neuvěřitelnou kondici horní i dolní poloviny těla." },
      { name: "Cyklistika", subtitle: "Gravel Biking", desc: "Rychlá jízda na pomezí silnice a terénu. 35 minut ostré jízdy v proměnlivém terénu je ideální H4 stimul pro nohy i srdce." },
      { name: "Hokej", subtitle: "Lední hokej / Florbal (hobby)", desc: "Vysoké tempo a intenzivní střídání simulující intervalový trénink. Pohyb na ledě či palubovce posouvá výkonnostní strop." },
      { name: "Běžky", subtitle: "Kondiční trénink", desc: "Plné soustředění na techniku odrazu a skluzu. Práce paží a nohou v chladu je výzvou budující železnou vytrvalost." },
      { name: "Triatlon", subtitle: "Sprint triatlon (příprava)", desc: "Střídání disciplín a nácvik přechodů. Komplexní příprava učí organismus rychlé adaptaci na různé typy zátěže." },
      { name: "Plavání", subtitle: "Trénink s pomůckami", desc: "Použití ploutví nebo pacek pro zvýšení odporu. Intervalové úseky budují specifickou sílu a nutí k efektivnějšímu dýchání." },
      { name: "Běh", subtitle: "Orientační běh", desc: "Běh v náročném lese s čtením mapy. Kombinace fyzické námahy v terénu a kognitivního zatížení dělá z běhu unikátní zážitek." },
      { name: "Frisbee", subtitle: "Ultimate Frisbee", desc: "Sport založený na sprintování a výskocích. Vysoká intenzita vyžaduje koordinaci a schopnost těla rychle regenerovat mezi akcemi." },
      { name: "Vodní pólo", subtitle: "Ragby / Vodní pólo (trénink)", desc: "Extrémní fyzická odolnost. I samotný dril ve vodě nebo sprinty na hřišti vás naučí pracovat v hlubokém kyslíkovém dluhu." },
      { name: "Gymnastika", subtitle: "Šerm / Moderní gymnastika", desc: "Intenzivní trénink vyžadující preciznost a výbušnost. Náročnost na hluboký stabilizační systém a srdeční činnost." },
      { name: "Zápas", subtitle: "Bojové sporty (kondiční)", desc: "Trénink technik a pohybu na žíněnce bez plného sparingu. Přetlačování a práce s těžištěm buduje funkční sílu a vytrvalost." },
    ],
  },
  h5: {
    subtitle: "Cesta k výkonu",
    description: "Tady už trénujete jako sportovci.",
    activities: [
      { name: "Běh", subtitle: "Trénink na 15 km / Tempové běhy", desc: "Ladění formy na konkrétní vzdálenost. Střídáte dlouhé souvislé běhy s tempovými úseky, které učí tělo hospodařit s energií." },
      { name: "Cyklistika", subtitle: "Kopcovitý terén", desc: "Delší vyjížďky s cíleným vyhledáváním kopců. Střídáním frekvence šlapání (síla vs. točení) rozvíjíte pomalá i rychlá svalová vlákna." },
      { name: "Plavání", subtitle: "Závodní trénink / Intervaly", desc: "Specifické série s krátkým odpočinkem. Tento typ zátěže buduje specifickou vytrvalost a učí držet techniku pod tlakem." },
      { name: "Cvičení", subtitle: "CrossFit (výkonnostní)", desc: "Plné nasazení v trénincích WOD. Kombinace silových a gymnastických prvků vede k výraznému nárůstu absolutní kondice." },
      { name: "Běh", subtitle: "Horský běh (intenzivní)", desc: "Běh v náročném terénu s velkým převýšením. Buduje silné nohy a učí srdce pracovat v proměnlivém rytmu podle sklonu." },
      { name: "Cyklistika", subtitle: "MTB XC / Trail", desc: "Pravidelný trénink techniky průjezdu. Střídání výjezdů s tepem na maximu a technických sjezdů je komplexní sportovní výkon." },
      { name: "Bojové sporty", subtitle: "Box / Thajský box (sparing)", desc: "Intenzivní trénink s partnerem. Extrémně náročné na dech a schopnost pracovat v hlubokém kyslíkovém dluhu." },
      { name: "Triatlon", subtitle: "Sprint triatlon (závodní ambice)", desc: "Příprava na konkrétní závod. Cílem je závodit, což vyžaduje schopnost rychle přepínat mezi různými typy svalové práce." },
      { name: "Běh", subtitle: "Překážkový běh (Spartan Sprint)", desc: "Kombinace běhu s nošením břemen a šplhem. Trénink buduje komplexní postavu pro nepředvídatelné výzvy." },
      { name: "Lezení", subtitle: "Výkonnostní úroveň", desc: "Lezení těžších cest, kde bojujete s laktátem. Započítávejte čas strávený přímo ve stěně pod napětím." },
      { name: "Chůze", subtitle: "Rucking / Dlouhé túry", desc: "Chůze s batohem (10–20 % hmotnosti) v ostrém tempu v kopcích. Buduje železnou odolnost těla bez velkých nárazů." },
      { name: "Parkour", subtitle: "Pokročilá úroveň", desc: "Plynulý pohyb městem s akrobatickými prvky. Vyžaduje výbušnost, koordinaci a sílu středu těla." },
      { name: "Bruslení", subtitle: "Rychlobruslení / Inline", desc: "Pravidelný trénink se zaměřením na techniku odrazu a nízký postoj. Práce v konstantním napětí stehen buduje specifickou sílu." },
      { name: "Vodní slalom", subtitle: "Trénink na divoké vodě", desc: "Boj s proudem vyžaduje extrémní sílu trupu a paží. Každý nájezd do branky je explozivním výkonem posouvajícím kondici." },
      { name: "Atletika", subtitle: "Atletický víceboj / Dráha", desc: "Specifický trénink na stadionu zaměřený na rychlostní vytrvalost a techniku. Nekompromisní k vašemu kardiovaskulárnímu systému." },
      { name: "Duatlon", subtitle: "Běh-Kolo-Běh", desc: "Intenzivní trénink přechodů pro ty, kteří neplavou. Učí nohy pracovat v různých režimech bez pauzy." },
      { name: "Lyžování", subtitle: "Skialpinismus (sportovní)", desc: "Náročné výstupy s velkým převýšením. Ostré stoupání budující obrovskou kapacitu plic a sílu celého těla." },
      { name: "Trenažér", subtitle: "Pádlování / Kayak Erg", desc: "Intenzivní veslování nebo pádlování budující sílu trupu a paží, nezbytnou pro triatlon i funkční zdraví." },
    ],
  },
  h6: {
    subtitle: "Brána k vytrvalosti",
    description: "Tělo se stává vysoce ekonomickým strojem.",
    activities: [
      { name: "Běh", subtitle: "Půlmaratonský trénink", desc: "Trénujete ekonomiku pohybu a schopnost udržet stabilitu v únavě. Dlouhé běhy v terénu prověří vaši psychickou odolnost." },
      { name: "Cyklistika", subtitle: "Objemové tréninky do 100 km", desc: "Budování základní vytrvalosti v sedle. Učí tělo efektivněji oxidovat tuky jako palivo a připravuje šlachy na zátěž." },
      { name: "Turistika", subtitle: "Vysokohorská turistika", desc: "Náročné výstupy s batohem. Vertikální metry budují robustní sílu nohou a učí vás hospodařit s dechem v náročném terénu." },
      { name: "Plavání", subtitle: "Open water (dlouhé tréninky)", desc: "Trénink na otevřené vodě bez stěn simuluje závodní podmínky a buduje psychickou stabilitu i vytrvalostní stimulus." },
      { name: "Cyklistika", subtitle: "MTB maraton (50–60 km)", desc: "Trénink na závody v terénu kombinující vytrvalost s technikou. Zvládání výjezdů s tepem nadoraz i technických sjezdů." },
      { name: "Běžky", subtitle: "Objemové tréninky", desc: "52 minut v bílé stopě zapojí celé tělo. Plynulý skluz a rytmus rozvíjejí kapacitu plic a celkovou zdatnost v zimě." },
      { name: "Triatlon", subtitle: "Olympijský triatlon (trénink)", desc: "Kombinování disciplín (např. plavání + běh). Učíte se přechody mezi různými typy svalové práce (tzv. přechodové tréninky)." },
      { name: "Lyžování", subtitle: "Skialpinismus (náročné trasy)", desc: "Výstupy ve volném terénu s velkým převýšením. Práce proti gravitaci a sněhu je budovatelem vytrvalostního základu." },
      { name: "Běh", subtitle: "Spartan Super / Beast trénink", desc: "Kombinace běhu v terénu se silovými prvky (nošení břemen). Simulace náročnosti dlouhých překážkových závodů." },
      { name: "Veslování", subtitle: "Dlouhé objemové tréninky", desc: "Rytmus a síla záběru po delší časový úsek. Vynikající pro trup a paže, buduje vytrvalost bez dopadů na klouby." },
      { name: "Adventure Race", subtitle: "Základní příprava", desc: "Kombinace různých aktivit v jednom bloku (kolo, běh, kanoistika). Učíte se být univerzálním sportovcem pro jakékoliv podmínky." },
      { name: "Cyklistika", subtitle: "Gravel grinding", desc: "Dlouhé jízdy v mírném terénu (3+ hodiny). Budování 'sedací vytrvalosti' a trénink v zóně spalování tuků." },
      { name: "Plavání", subtitle: "Sériový bazénový trénink", desc: "Např. 5x 500 m s minimální pauzou. Vytrvalostní dril nezbytný pro posun k dálkovému plavání a H7." },
      { name: "Kanoistika", subtitle: "Kondiční kanoistika / Kayak", desc: "Souvislé pádlování po dlouhou dobu pro vytrvalost horní poloviny těla, kterou běžci často zanedbávají." },
    ],
  },
  h7: {
    subtitle: "Život v pohybu",
    description: "Vrchol systému. Hodina denně jako automatický standard a radost.",
    activities: [
      { name: "Cyklistika", subtitle: "Závodní objemová vytrvalost", desc: "60 minut v sedle je standardem učícím tělo maximální ekonomice a efektivnímu spalování tuků pro dlouhé výkony." },
      { name: "Běh", subtitle: "Maratonský trénink", desc: "Pravidelné tréninky střídající intenzity. Vědomá práce s běžeckou formou a budování psychické odolnosti pro extrémní distance." },
      { name: "Cyklistika", subtitle: "MTB maraton (80–100 km)", desc: "Intenzivní jízda v náročném terénu prověřující techniku i energetickou zdatnost. Příprava na celodenní výzvy." },
      { name: "Míčové hry", subtitle: "Závodní příprava (Fotbal / Basketbal)", desc: "Hra na vysoké úrovni vyžadující výbušnost a rychlou regeneraci. Plnohodnotný sportovní výkon s důrazem na taktiku." },
      { name: "Triatlon", subtitle: "Závodní výkonnost", desc: "Ladění formy ve všech disciplínách. Pilování přechodů, aby tělo fungovalo jako jeden sehraný stroj připravený na olympijskou distanci." },
      { name: "Plavání", subtitle: "Dálkové plavání (trénink na 10 km)", desc: "Schopnost udržet tempo a techniku po celou hodinu bez zastavení. Buduje neuvěřitelnou kapacitu plic." },
      { name: "Běh", subtitle: "Závodní běh do vrchu", desc: "Nekompromisní souboj s gravitací. Buduje extrémní sílu nohou a učí srdce pracovat na hranici maximálních možností." },
      { name: "Hokej", subtitle: "Výkonnostní hokej", desc: "Rychlá a tvrdá hra vyžadující koncentraci a sílu. Intervalové střídání v tempu udržuje kardiovaskulární systém v absolutní špičce." },
      { name: "Biatlon", subtitle: "Amatérská pravidelná příprava", desc: "Kombinace vysokého tepu z běhu a klidu při střelbě. Učí sebekontrole a ovládání dechu pod maximálním tlakem." },
      { name: "Triatlon", subtitle: "Half Ironman příprava", desc: "Systematické skládání hodin pro zvládnutí nároků polovičního Ironmana. Ekonomické minimum, které vás bezpečně dovede do cíle." },
      { name: "Cvičení", subtitle: "Brick Training (přechody)", desc: "Bezprostřední kombinace dvou disciplín (např. kolo + běh) bez pauzy. Učíte tělo zvládnout změnu typu zátěže." },
      { name: "Kombinace", subtitle: "Ride & Run", desc: "Praktické spojení dopravy a sportu. Dojet na kole do terénu a tam absolvovat běžecký trénink pro rozvoj všestrannosti." },
      { name: "Posilování", subtitle: "Silový dril pro vytrvalce", desc: "Cílené zvedání těžších vah (dřepy, mrtvé tahy) pro prevenci zranění a pevnost šlach při obrovském ročním objemu pohybu." },
    ],
  },
};

const EN_DETAILS: LevelActivityDetails = {
  h1: {
    subtitle: "Starting step",
    description: "The goal is to wake up the body and build a basic habit.",
    activities: [
      { name: "Walking", subtitle: "Brisk walking (4–6 km/h)", desc: "Walk at the pace you'd use if you were rushing to an important meeting. Your breathing should speed up enough that you can still talk, but couldn't sing smoothly." },
      { name: "H7 Movement", subtitle: "Universal activity", desc: "For all the unexpected moments of the day when you're noticeably out of breath (catching transit, hurrying through town) but the activity has no specific name." },
      { name: "Exercise", subtitle: "Active home-office breaks", desc: "Instead of coffee, slot in 9 minutes of squats, desk push-ups or dynamic stretching. This short block is enough to oxygenate the brain and activate the heart." },
      { name: "Stairs", subtitle: "Climbing the stairs", desc: "Use the stairwell as your personal trainer. Move at a steady pace without stopping and focus on a deep exhale on every step." },
      { name: "Garden", subtitle: "Medium-load gardening", desc: "Raking leaves, planting or tidying flower beds. It counts when you're in continuous motion, engaging muscles, and feeling slightly out of breath." },
      { name: "Play", subtitle: "Playful movement with kids or pets", desc: "Intense games of tag, wrestling on the rug or active ball-throwing. You activate the heart naturally through emotion, without registering the effort." },
      { name: "Hiking", subtitle: "Hiking on gently rolling terrain", desc: "Climbing naturally forces the lungs to work harder. Keep a brisk pace and feel the stabilising muscles activate." },
      { name: "Cycling", subtitle: "Recreational riding on flat ground", desc: "Focus on smooth pedalling without long pauses. The activity meets H1 the moment your breath becomes rhythmic and deeper than at rest." },
      { name: "Cleaning", subtitle: "Dynamic household cleaning", desc: "Vacuuming, mopping or window cleaning done at an energetic pace. Use broad arm motions so the heart gets working." },
      { name: "Trainer", subtitle: "Elliptical / Cross-trainer", desc: "Ideal for beginners thanks to the absence of joint impact. Set a mild resistance and keep the pace where only short conversation is possible." },
      { name: "Nordic Walking", subtitle: "Walking with poles", desc: "Proper technique engages up to 90 % of muscles. The active push-off helps you naturally quicken the step and deepen breathing." },
      { name: "Swimming", subtitle: "Basic swimming and technique", desc: "Focus on smooth motion and exhaling into the water. It's enough to keep a constant pace where you feel the gentle resistance and a raised pulse." },
      { name: "Water Walking", subtitle: "Aquawalking in waist-deep water", desc: "Water resistance increases the difficulty of every step. An easy and safe way to activate the heart even at a seemingly slow pace." },
      { name: "Yoga", subtitle: "Active and dynamic forms (e.g. Vinyasa)", desc: "Counts only when the pace is such that you feel inner heat rising and breathing rate noticeably increases." },
      { name: "Scooter", subtitle: "Recreational scooter ride", desc: "Switch the kick-off leg regularly and keep a pace that forces deeper breathing. Don't count passive coasting downhill." },
      { name: "Dancing", subtitle: "Social or living-room dancing", desc: "Movement must engage the whole body, arms included. Dance intensely enough that after each track you're pleasantly out of breath." },
      { name: "Cycling", subtitle: "Trainer / Stationary bike", desc: "Riding in the aerobic zone with smooth rotation against mild resistance. Maintain effort that makes you lightly sweat." },
      { name: "Golf", subtitle: "Playing while carrying the bag", desc: "Count only the minutes of brisk walking between holes with the bag on your back. Bag weight is the factor that lifts the heart to H1." },
      { name: "Tai-chi", subtitle: "Dynamic form", desc: "Must be done in deeper stances with conscious whole-body engagement, leading to inner warming and deeper breathing." },
    ],
  },
  h2: {
    subtitle: "Stability step",
    description: "Building the habit. Movement becomes part of your identity.",
    activities: [
      { name: "Strength Training", subtitle: "Bodyweight exercises", desc: "Basic moves like squats, planks or lunges at a controlled pace. Count only the net time spent under muscle tension with an elevated pulse." },
      { name: "Cycling", subtitle: "Road and paved trails", desc: "Smooth pace on flat ground or gentle terrain (touring conversational effort). You feel the thighs working and breathing is deep but you can still talk." },
      { name: "Commute", subtitle: "Active commuting (bike/scooter)", desc: "Turn the trip to work into a training block. The most effective way to slot daily movement that naturally gets you out of breath." },
      { name: "Garden", subtitle: "Heavy garden work", desc: "Digging, turning compost or pushing loaded wheelbarrows. Count the minutes when you are in continuous motion and feel a real demand on your lungs." },
      { name: "Running", subtitle: "Indian running", desc: "Alternating 1 minute of light jogging with 2 minutes of walking. Spares the joints and lets the heart gradually adapt to higher load. Gradually extend the run portion." },
      { name: "Walking", subtitle: "Power walking on terrain", desc: "Gentle hills that naturally raise the heart rate without running. Working against gravity is excellent for the cardiovascular system without hard impacts." },
      { name: "Swimming", subtitle: "Multiple strokes with rest", desc: "Alternate breaststroke, backstroke and crawl with short pauses. The key is smoothness and exhaling into the water, which taxes the lungs even at a lower pace." },
      { name: "Pilates", subtitle: "Core-focused training", desc: "Focus on core control and precise breathing. Muscle engagement must bring on a sense of inner heat and a faster heartbeat." },
      { name: "Badminton", subtitle: "Recreational play", desc: "Even in a meadow game you'll break a real sweat chasing the shuttle and working on your toes. Keep play moving with minimal pauses." },
      { name: "Skating", subtitle: "Inline or ice", desc: "Smooth joint-sparing motion that engages the stabiliser system. Skate on ice only if you have the motion down. Keep a conversational pace." },
      { name: "Table Tennis", subtitle: "Recreational play", desc: "Active footwork and shifts of weight. Count the time of actual play in constant readiness, not the time spent picking balls off the floor." },
      { name: "Dog Training", subtitle: "Dog Agility / Active training", desc: "Running alongside the dog over obstacles. Emotion helps you forget the effort while breathing and pulse rise naturally." },
      { name: "Water Exercise", subtitle: "Aqua aerobics / Aqua-jogging", desc: "Use water resistance to strengthen the body without overloading tendons. Running the pool floor or using a belt reliably keeps the heart in the healthy-motion zone." },
      { name: "Skiing", subtitle: "Downhill skiing", desc: "Count only the net minutes of active descent while the leg muscles are working. Lift time and queues are relaxation (H0)." },
      { name: "Cross-country Skiing", subtitle: "Classic style", desc: "Groomed tracks and flat terrain for a touring pace. Simultaneous arm and leg work efficiently activates the whole body." },
      { name: "Trampoline", subtitle: "Gentle jumps and bouncing", desc: "A great way to get the lymph flowing and strengthen the core. You'll feel deeper breathing and an endorphin kick." },
      { name: "Ball Games", subtitle: "Volleyball / Footvolley", desc: "Count the clean set time with active engagement on your toes. The game must flow so breathing rate stays steadily elevated." },
      { name: "Trainer", subtitle: "Stairstepper / Step machine", desc: "A pace that mimics a calm uphill climb. Handrails are only for balance. The goal is a constant, mildly breath-increasing rhythm." },
      { name: "Walking", subtitle: "Plogging (walking with litter pickup)", desc: "A mix of brisk walking with constant squats and bends. Activates the metabolism more comprehensively than ordinary walking." },
      { name: "Rowing", subtitle: "Trainer or water", desc: "A steady stroke pace with emphasis on the leg drive and smooth breathing. Stay in the comfortable conversational zone." },
      { name: "Climbing", subtitle: "Bouldering for beginners", desc: "Easy routes that demand smooth upward motion. Count the climbing moments when muscle tension raises the demand on breath." },
      { name: "Basketball", subtitle: "Solo shooting practice", desc: "Active shooting paired with chasing your own rebounds. Keeps the heart working without the exhaustion of a 3-on-3 game." },
      { name: "Water Sports", subtitle: "Canoeing / SUP", desc: "Rhythmic paddle strokes on calm water engaging trunk rotation. Ideal for stability and mild breathing activation outdoors." },
      { name: "Walking", subtitle: "Snowshoes on flat terrain", desc: "Movement through deep snow creates resistance and raises the demand of each step. Lets you keep a smooth pace with deeper breathing." },
      { name: "Bat-and-Ball", subtitle: "Softball / Baseball", desc: "Count only the minutes of active running, pitching or batting. Most of the game is static, so add up only the bursts with an elevated pulse." },
    ],
  },
  h3: {
    subtitle: "Fitness step",
    description: "Movement becomes joyful. Here we start to build real fitness.",
    activities: [
      { name: "Exercise", subtitle: "Aerobics / Zumba / Bodyform", desc: "Group classes whose music and rhythm keep you at a steady fitness pace. The most accessible form of organised exercise." },
      { name: "Running", subtitle: "Jogging / Slow running", desc: "The cornerstone of endurance with a light footstrike. Enjoy moving through the landscape and increase route length by no more than 5–10 % a week." },
      { name: "Circuit Training", subtitle: "Intense exercise rotation", desc: "Different muscle groups with minimal rest. Keeps the heart in the optimal fitness zone and efficiently builds strength and endurance." },
      { name: "Ball Games", subtitle: "Football / Floorball / Basketball", desc: "Recreational matches on a smaller court with interval character. Short sprints and direction changes push you into the active-breathing zone." },
      { name: "Tennis", subtitle: "Recreational level", desc: "Active play across the whole court focused on footwork. Flowing rallies keep the circulation in constant motion." },
      { name: "Cycling", subtitle: "Spinning / Indoor bike", desc: "Intense pedalling in a controlled environment with music or apps. Full focus on output and breathing without outside distractions." },
      { name: "Swimming", subtitle: "Fitness swimming", desc: "Continuous swimming of several pool lengths alternating strokes (breast, back). Minimise wall pauses to keep the pulse in the fitness zone." },
      { name: "Yoga", subtitle: "Power yoga", desc: "Dynamic flow of postures in sync with breath that demands strength and stability. Breathing must be deep and consciously quicker throughout." },
      { name: "Exercise", subtitle: "TRX / Kettlebell", desc: "Functional training with implement resistance. Technical precision and short rest intervals keep the heart active and muscles under tension." },
      { name: "Walking", subtitle: "Rucking (walking with a loaded pack)", desc: "Brisk walking with a backpack (5–15 % of bodyweight). Efficient fitness building that spares the joints yet taxes the lungs like jogging." },
      { name: "Hiking", subtitle: "Mountain hiking (steep)", desc: "Faster walking on broken terrain with significant elevation. Working against gravity reliably drives a high heart rate." },
      { name: "Dancing", subtitle: "Latino / Intense class", desc: "Energetic routines like salsa demanding fast footwork and trunk motion. Moving to the beat keeps you in the fitness-breathing zone." },
      { name: "Stairs", subtitle: "Intense training", desc: "Deliberate running or very fast walking up stairs (two at a time). The quickest way to test your engine and leg strength." },
      { name: "Martial Arts", subtitle: "Judo / Karate – basic training", desc: "Technique drills in motion, shadow fighting or light fitness sparring. Explosive movements reliably fire up the cardiovascular system." },
      { name: "Skiing", subtitle: "Ski-touring (light terrain)", desc: "Uphill skiing engaging the whole body. Snow resistance and pole work put you in the deeper fitness-breathing zone." },
      { name: "Riding", subtitle: "Skate / Longboard", desc: "Active movement through the city with frequent pushing. Count the time of active pushing or weight-shifting, not passive coasting." },
      { name: "Dancing", subtitle: "Pole dance (fitness)", desc: "Strength-acrobatic pole work demanding core bracing. Count the practice time of elements that force deep breathing." },
      { name: "Swimming", subtitle: "Open water (natural swimming)", desc: "Continuous motion in open water without walls. More demanding on navigation and thermoregulation, which makes swimming an excellent fitness activity." },
    ],
  },
  h4: {
    subtitle: "Sustainable middle",
    description: "The H7 gold standard. This is where lifelong health is won.",
    activities: [
      { name: "Exercise", subtitle: "Tabata / HIIT", desc: "High-intensity interval training for maximum burn. Alternating max effort with short rest keeps the metabolism fired up." },
      { name: "Running", subtitle: "Systematic training", desc: "Alternating distance and intensity (e.g. fartlek). Teaches the body to work efficiently under longer load when the inner diesel must run full-tilt." },
      { name: "Tennis", subtitle: "Regular training / Badminton", desc: "Stroke drills and game tactics. Constant movement combined with technique makes the session a very intense unit." },
      { name: "Exercise", subtitle: "CrossFit", desc: "A mix of gymnastics, weightlifting and cardio. You focus on technique and flow within the workout of the day (WOD), which tests both strength and endurance." },
      { name: "Cycling", subtitle: "Mountain bike (MTB)", desc: "Trail riding demands both strength and technique. Every root and climb becomes a natural interval for legs, trunk and arms." },
      { name: "Running", subtitle: "Trail Running", desc: "Running off pavement over obstacles. Requires far more stability and strength than road running. Terrain climbs build robust fitness." },
      { name: "Running", subtitle: "Running with a stroller", desc: "Longer routes under load significantly raise the demand on core and arms. Combines childcare with quality endurance training." },
      { name: "Rowing", subtitle: "Intense training", desc: "A strong leg drive and smooth breathing. A full-body load that builds muscular endurance and lung capacity without impact." },
      { name: "Squash", subtitle: "Explosive movement with direction changes", desc: "The interval character is great for fat burning and heart strengthening. The pace gets you into H4 very quickly." },
      { name: "Combat Sports", subtitle: "Boxing / Kickbox (fitness)", desc: "Bag work or pad work in explosive sequences. Builds incredible fitness in both upper and lower body." },
      { name: "Cycling", subtitle: "Gravel Biking", desc: "Fast riding between road and trail. 35 minutes of sharp riding on variable terrain is an ideal H4 stimulus for legs and heart." },
      { name: "Hockey", subtitle: "Ice hockey / Floorball (hobby)", desc: "High pace and intense shifts mimicking an interval workout. Ice or floor play pushes the performance ceiling." },
      { name: "Cross-country Skiing", subtitle: "Fitness training", desc: "Full focus on kick and glide technique. Working arms and legs in the cold is a challenge that builds iron endurance." },
      { name: "Triathlon", subtitle: "Sprint triathlon (preparation)", desc: "Alternating disciplines and practising transitions. Comprehensive preparation teaches the body to adapt quickly between load types." },
      { name: "Swimming", subtitle: "Training with tools", desc: "Using fins or paddles to add resistance. Interval sets build specific strength and force more efficient breathing." },
      { name: "Running", subtitle: "Orienteering", desc: "Running in demanding forest with map reading. The blend of physical effort and cognitive load makes it a unique experience." },
      { name: "Frisbee", subtitle: "Ultimate Frisbee", desc: "A sport based on sprints and jumps. The high intensity demands coordination and fast body recovery between plays." },
      { name: "Water Polo", subtitle: "Rugby / Water Polo (training)", desc: "Extreme physical resilience. Even the water drills or pitch sprints teach you to work in deep oxygen debt." },
      { name: "Gymnastics", subtitle: "Fencing / Modern gymnastics", desc: "Intense training demanding precision and explosiveness. Taxing on the deep stabiliser system and the heart." },
      { name: "Wrestling", subtitle: "Combat sports (fitness)", desc: "Technique and movement drills on the mat without full sparring. Pushing and centre-of-mass work builds functional strength and endurance." },
    ],
  },
  h5: {
    subtitle: "Road to performance",
    description: "Here you're training like athletes.",
    activities: [
      { name: "Running", subtitle: "15 km training / Tempo runs", desc: "Peaking your form for a specific distance. You alternate long steady runs with tempo segments that teach the body to manage energy." },
      { name: "Cycling", subtitle: "Hilly terrain", desc: "Longer rides deliberately seeking out hills. Alternating cadence (power vs. spin) develops both slow and fast muscle fibres." },
      { name: "Swimming", subtitle: "Race training / Intervals", desc: "Specific sets with short rest. This load builds specific endurance and trains you to hold technique under pressure." },
      { name: "Exercise", subtitle: "CrossFit (performance)", desc: "Full commitment in WOD sessions. The mix of strength and gymnastic elements produces a major jump in absolute fitness." },
      { name: "Running", subtitle: "Mountain running (intense)", desc: "Running demanding terrain with large elevation gain. Builds strong legs and trains the heart to handle variable rhythm by slope." },
      { name: "Cycling", subtitle: "MTB XC / Trail", desc: "Regular trail-technique training. Alternating climbs at max heart rate with technical descents is a complete sports performance." },
      { name: "Combat Sports", subtitle: "Boxing / Muay Thai (sparring)", desc: "Intense partner training. Extremely demanding on breath and the ability to operate in deep oxygen debt." },
      { name: "Triathlon", subtitle: "Sprint triathlon (racing ambition)", desc: "Preparation for a specific race. The goal is to race, which requires fast switching between different kinds of muscle work." },
      { name: "Running", subtitle: "Obstacle race (Spartan Sprint)", desc: "A mix of running with load carrying and climbing. The training builds a complete body for unpredictable challenges." },
      { name: "Climbing", subtitle: "Performance level", desc: "Climbing harder routes where you fight lactate. Count the time spent on the wall under tension." },
      { name: "Walking", subtitle: "Rucking / Long treks", desc: "Walking with a pack (10–20 % of bodyweight) at a sharp pace in the hills. Builds iron body resilience without big impact." },
      { name: "Parkour", subtitle: "Advanced level", desc: "Smooth city movement with acrobatic elements. Demands explosiveness, coordination and core strength." },
      { name: "Skating", subtitle: "Speed skating / Inline", desc: "Regular training focused on push-off technique and low stance. Working thighs in constant tension builds specific strength." },
      { name: "Water Slalom", subtitle: "Training on wild water", desc: "Fighting the current demands extreme trunk and arm strength. Every gate run is an explosive effort pushing fitness forward." },
      { name: "Athletics", subtitle: "Combined events / Track", desc: "Specific stadium training focused on speed endurance and technique. Uncompromising to your cardiovascular system." },
      { name: "Duathlon", subtitle: "Run-Bike-Run", desc: "Intense transition training for non-swimmers. Teaches the legs to work across different modes without a pause." },
      { name: "Skiing", subtitle: "Ski-touring (sport)", desc: "Demanding climbs with large elevation. Sharp ascents that build massive lung capacity and whole-body strength." },
      { name: "Trainer", subtitle: "Paddling / Kayak Erg", desc: "Intense rowing or paddling that builds the trunk and arm strength essential for triathlon and functional health." },
    ],
  },
  h6: {
    subtitle: "Gateway to endurance",
    description: "The body becomes a highly economical machine.",
    activities: [
      { name: "Running", subtitle: "Half-marathon training", desc: "You're training movement economy and the ability to hold stability under fatigue. Long trail runs test mental resilience." },
      { name: "Cycling", subtitle: "Volume training up to 100 km", desc: "Building base endurance in the saddle. Teaches the body to oxidise fat more efficiently as fuel and preps the tendons for load." },
      { name: "Hiking", subtitle: "Alpine hiking", desc: "Demanding ascents with a pack. Vertical metres build robust leg strength and teach you to manage breath on hard terrain." },
      { name: "Swimming", subtitle: "Open water (long training)", desc: "Training in open water without walls simulates race conditions and builds mental stability alongside endurance stimulus." },
      { name: "Cycling", subtitle: "MTB marathon (50–60 km)", desc: "Training for off-road races combining endurance with technique. Managing all-out climbs and technical descents alike." },
      { name: "Cross-country Skiing", subtitle: "Volume training", desc: "52 minutes in the white track engages the whole body. Smooth glide and rhythm develop lung capacity and winter fitness overall." },
      { name: "Triathlon", subtitle: "Olympic triathlon (training)", desc: "Combining disciplines (e.g. swim + run). You learn transitions between different kinds of muscle work (brick workouts)." },
      { name: "Skiing", subtitle: "Ski-touring (advanced routes)", desc: "Open-terrain climbs with large elevation. Working against gravity and snow is a true builder of the endurance base." },
      { name: "Running", subtitle: "Spartan Super / Beast training", desc: "Trail running combined with strength elements (load carries). Simulates the demands of long obstacle races." },
      { name: "Rowing", subtitle: "Long volume training", desc: "Rhythm and stroke strength over a longer stretch. Excellent for the trunk and arms, builds endurance without joint impact." },
      { name: "Adventure Race", subtitle: "Foundation training", desc: "A mix of different activities in one block (bike, run, canoe). You learn to be an all-round athlete for any conditions." },
      { name: "Cycling", subtitle: "Gravel grinding", desc: "Long rides on mild terrain (3+ hours). Building saddle endurance and training in the fat-burn zone." },
      { name: "Swimming", subtitle: "Pool set training", desc: "For example 5 × 500 m with minimal rest. The endurance drill essential to progress toward distance swimming and H7." },
      { name: "Canoeing", subtitle: "Fitness canoeing / Kayak", desc: "Continuous paddling over a long stretch for upper-body endurance that runners often neglect." },
    ],
  },
  h7: {
    subtitle: "Life in motion",
    description: "The peak of the system. An hour a day as an automatic standard — and a joy.",
    activities: [
      { name: "Cycling", subtitle: "Race volume endurance", desc: "60 minutes in the saddle is the standard that teaches the body maximum economy and efficient fat burn for long performances." },
      { name: "Running", subtitle: "Marathon training", desc: "Regular sessions alternating intensities. Conscious work on running form and building mental resilience for extreme distances." },
      { name: "Cycling", subtitle: "MTB marathon (80–100 km)", desc: "Intense riding in demanding terrain that tests technique and energy fitness. Preparation for all-day challenges." },
      { name: "Ball Games", subtitle: "Competitive preparation (Football / Basketball)", desc: "High-level play demanding explosiveness and fast recovery. A full sports performance with emphasis on tactics." },
      { name: "Triathlon", subtitle: "Race performance", desc: "Tuning form across all disciplines. Polishing transitions so the body works as one well-oiled machine ready for the Olympic distance." },
      { name: "Swimming", subtitle: "Long-distance swimming (10 km training)", desc: "The ability to hold pace and technique for a full hour without stopping. Builds incredible lung capacity." },
      { name: "Running", subtitle: "Uphill race running", desc: "An uncompromising fight with gravity. Builds extreme leg strength and trains the heart to work at the edge of maximum." },
      { name: "Hockey", subtitle: "Performance hockey", desc: "Fast, hard play demanding focus and strength. Interval shifts at pace keep the cardiovascular system at absolute peak." },
      { name: "Biathlon", subtitle: "Amateur regular preparation", desc: "A blend of high running heart rate and calm shooting. Teaches self-control and breath mastery under maximum pressure." },
      { name: "Triathlon", subtitle: "Half Ironman preparation", desc: "Systematic stacking of hours to handle the demands of the Half Ironman. The economical minimum that safely gets you to the finish." },
      { name: "Exercise", subtitle: "Brick Training (transitions)", desc: "An immediate combination of two disciplines (e.g. bike + run) with no pause. Teaches the body to handle a change in load type." },
      { name: "Combination", subtitle: "Ride & Run", desc: "A practical pairing of transport and sport. Cycle out to the terrain and do the running session there for all-round development." },
      { name: "Strength Training", subtitle: "Strength drill for endurance athletes", desc: "Deliberate heavier lifts (squats, deadlifts) for injury prevention and tendon toughness under a huge yearly movement volume." },
    ],
  },
};

const SK_DETAILS: LevelActivityDetails = {
  h1: {
    subtitle: "Štartovací schod",
    description: "Cieľom je prebudiť telo a vytvoriť základný návyk.",
    activities: [
      { name: "Chôdza", subtitle: "Rýchla chôdza (4–6 km/h)", desc: "Choďte tempom, akoby ste sa ponáhľali na dôležité stretnutie. Vaše dýchanie sa musí zrýchliť natoľko, že síce zvládnete rozprávať, ale už by ste nedokázali plynulo spievať." },
      { name: "Pohyb H7", subtitle: "Univerzálna aktivita", desc: "Pre všetky nečakané momenty dňa, keď sa citeľne zadýchate (dobiehanie dopravy, rýchly presun mestom), ale aktivita nemá špecifický názov." },
      { name: "Cvičenie", subtitle: "Aktívne home-office prestávky", desc: "Namiesto kávy zaraďte 9 minút drepov, klikov o stôl alebo dynamického preťahovania. Tento krátky blok stačí na okysličenie mozgu a aktiváciu srdca." },
      { name: "Schody", subtitle: "Chôdza po schodoch", desc: "Využite schodisko ako osobný trenažér. Choďte plynulým tempom bez zastavovania a sústreďte sa na hlboký výdych pri každom kroku." },
      { name: "Záhrada", subtitle: "Záhradné práce strednej záťaže", desc: "Hrabanie lístia, sadenie alebo úprava záhonov. Počíta sa, ak ste v neustálom pohybe, zapájate svaly a cítite mierne zadýchanie." },
      { name: "Hra", subtitle: "Hravý pohyb s deťmi alebo mazlíčkami", desc: "Intenzívna hra na naháňačku, zápasenie na koberci alebo aktívne hádzanie loptičky. Aktivujete srdce prirodzene cez emócie, bez toho aby ste vnímali námahu." },
      { name: "Turistika", subtitle: "Pešia turistika v mierne zvlnenom teréne", desc: "Stúpanie prirodzene núti pľúca k hlbšej práci. Udržujte svižné tempo a vnímajte aktiváciu stabilizačných svalov." },
      { name: "Cyklistika", subtitle: "Rekreačná jazda po rovine", desc: "Sústreďte sa na plynulé šliapanie bez dlhých prestávok. Aktivita spĺňa H1 vo chvíli, keď cítite, že dych je rytmický a hlbší než v pokoji." },
      { name: "Upratovanie", subtitle: "Dynamické domáce upratovanie", desc: "Vysávanie, vytieranie podlahy alebo umývanie okien vykonávané v energickom tempe. Zapájajte široké pohyby paží, aby sa srdce rozpracovalo." },
      { name: "Trenažér", subtitle: "Elliptical / Orbitrek", desc: "Ideálny pre začiatočníkov vďaka eliminácii nárazov na kĺby. Nastavte mierny odpor a udržujte tempo, pri ktorom zvládate len krátku konverzáciu." },
      { name: "Nordic Walking", subtitle: "Chôdza s palicami", desc: "Správna technika zapojí až 90 % svalov. Aktívny odpich vám pomôže prirodzene zrýchliť krok a prehĺbiť dýchanie." },
      { name: "Plávanie", subtitle: "Základné plávanie a technika", desc: "Sústreďte sa na plynulý pohyb a výdych do vody. Stačí udržať konštantné tempo, pri ktorom cítite jemný odpor vody a zvýšený tep." },
      { name: "Vodná chôdza", subtitle: "Aquawalking v bazéne s vodou po pás", desc: "Odpor vody zvyšuje náročnosť každého kroku. Jednoduchá a bezpečná metóda na aktiváciu srdca aj pri zdanlivo pomalom pohybe." },
      { name: "Joga", subtitle: "Aktívne a dynamické formy (napr. Vinyasa)", desc: "Započítava sa iba vtedy, ak je tempo také, že cítite nárast vnútorného tepla a dychová frekvencia sa hmatateľne zvýši." },
      { name: "Kolobežka", subtitle: "Rekreačná jazda na kolobežke", desc: "Pravidelne striedajte odrazovú nohu a udržujte tempo, ktoré vás núti k hlbšiemu dýchaniu. Nepočítajte pasívne zjazdy zo svahov." },
      { name: "Tanec", subtitle: "Spoločenský alebo domáci tanec", desc: "Pohyb musí zapojiť celé telo vrátane paží. Tancujte tak intenzívne, aby ste sa po každej skladbe cítili príjemne zadýchaní." },
      { name: "Cyklistika", subtitle: "Trenažér / Stacionárny bicykel", desc: "Jazda v aerobnom pásme s plynulou rotáciou proti miernemu odporu. Udržujte úsilie, pri ktorom sa ľahko zapotíte." },
      { name: "Golf", subtitle: "Hra s nosením bagu", desc: "Započítavajte iba minúty ostrej chôdze medzi jamkami s vybavením na chrbte. Záťaž bagu je faktorom, ktorý aktivuje srdce do úrovne H1." },
      { name: "Tai-chi", subtitle: "Dynamické prevedenie", desc: "Musí sa vykonávať v hlbších postojoch s vedomým silovým zapojením celého tela, ktoré vedie k vnútornému zahriatiu a prehĺbeniu dychu." },
    ],
  },
  h2: {
    subtitle: "Stabilizačný schod",
    description: "Budovanie návyku. Pohyb sa stáva súčasťou vašej identity.",
    activities: [
      { name: "Posilňovanie", subtitle: "Cvičenie s vlastnou váhou", desc: "Základné cviky ako drepy, plank alebo výpady v kontrolovanom tempe. Počítajte iba čistý čas cvičenia so svalovým napätím a zrýchleným tepom." },
      { name: "Cyklistika", subtitle: "Cestné a spevnené cesty", desc: "Plynulé tempo po rovine alebo v miernom teréne (výletné konverzačné úsilie). Cítite prácu stehien a dych je hlboký, ale stále môžete rozprávať." },
      { name: "Doprava", subtitle: "Aktívne dochádzanie (bicykel/kolobežka)", desc: "Využite cestu do práce ako tréningový blok. Najefektívnejší spôsob, ako do dňa vložiť pohyb, ktorý vás prirodzene zadýcha." },
      { name: "Záhrada", subtitle: "Ťažké záhradné práce", desc: "Rytie, prehadzovanie kompostu alebo vozenie naložených fúrikov. Počítajte minúty, keď ste v neustálom pohybe a cítite nárok na svoje pľúca." },
      { name: "Beh", subtitle: "Indiánsky beh", desc: "Striedanie 1 minúty ľahkého klusu a 2 minút chôdze. Šetrí kĺby a umožňuje srdcu plynule si zvykať na vyššiu záťaž. Postupne dobu behu predlžujte." },
      { name: "Chôdza", subtitle: "Power Walking v teréne", desc: "Mierne kopce, ktoré prirodzene zvýšia tep aj bez behu. Práca proti gravitácii je vynikajúca pre kardiovaskulárny systém bez tvrdých dopadov." },
      { name: "Plávanie", subtitle: "Rôzne štýly s oddychom", desc: "Striedajte prsia, znak a kraul s krátkymi pauzami. Kľúčom je plynulosť a výdych do vody, ktorý zvyšuje nároky na pľúca aj pri nižšom tempe." },
      { name: "Pilates", subtitle: "Cvičenie na stred tela", desc: "Sústreďte sa na kontrolu core a precízne dýchanie. Svalové napätie musí viesť k pocitu vnútorného tepla a zrýchleniu srdcového tepu." },
      { name: "Bedminton", subtitle: "Rekreačná hra", desc: "Aj pri hre na lúke sa pri dobiehaní košíčka a práci na špičkách slušne zapotíte. Udržujte hru v pohybe s minimom páuz." },
      { name: "Korčuľovanie", subtitle: "In-line alebo ľad", desc: "Plynulý pohyb šetriaci kĺby, vyžadujúci zapojenie stabilizačného systému. Na ľade športujte iba ak pohyb ovládate. Udržujte konverzačné tempo." },
      { name: "Stolný tenis", subtitle: "Rekreačná hra", desc: "Aktívny pohyb nohami a zmeny ťažiska. Počítajte čas samotnej hry v neustálom strehu, nie zbieranie loptičiek pod stolom." },
      { name: "Tréning psa", subtitle: "Dog Agility / Aktívny tréning", desc: "Behanie popri psovi cez prekážky. Emócie pomáhajú zabudnúť na námahu, dych a tep idú prirodzene nahor." },
      { name: "Vodné cvičenie", subtitle: "Aqua aerobik / Aqua-jogging", desc: "Využitie odporu vody na posilnenie tela bez preťaženia šliach. Beh po dne alebo s pásom spoľahlivo udrží srdce v zóne zdravého pohybu." },
      { name: "Lyžovanie", subtitle: "Zjazdové lyžovanie", desc: "Počítajte iba čisté minúty aktívneho zjazdu, keď svaly nôh pracujú. Čas na lanovke alebo v rade je relax (H0)." },
      { name: "Bežky", subtitle: "Klasický štýl", desc: "Upravená stopa a rovinatý terén pre výletné tempo. Zapojenie paží aj nôh súčasne efektívne aktivuje celé telo." },
      { name: "Trampolína", subtitle: "Mierne skoky a pohupovanie", desc: "Skvelý spôsob na rozprúdenie lymfy a posilnenie stredu tela. Cítite prehĺbený dych a nástup endorfínov." },
      { name: "Loptové hry", subtitle: "Volejbal / Nohejbal", desc: "Započítavajte čistý čas setov v aktívnom zapojení na špičkách. Hra musí mať spád pre trvalé mierne zvýšenie dychovej frekvencie." },
      { name: "Trenažér", subtitle: "Stairstepper / Schodový trenažér", desc: "Tempo simulujúce pokojný výstup do kopca. Ruky držadlá iba istia. Cieľom je konštantný, mierne zadýchavajúci rytmus." },
      { name: "Chôdza", subtitle: "Plogging (chôdza so zberom odpadkov)", desc: "Kombinácia rýchlej chôdze s neustálymi drepmi a predklonmi. Aktivuje metabolizmus komplexnejšie ako bežná chôdza." },
      { name: "Veslovanie", subtitle: "Trenažér aj voda", desc: "Stabilné tempo záberov s dôrazom na odraz nôh a plynulé dýchanie. Strážte si, aby ste zostali v komfortnej konverzačnej zóne." },
      { name: "Lezenie", subtitle: "Bouldering pre začiatočníkov", desc: "Ľahké cesty nútiace k plynulému pohybu nahor. Počítajte momenty lezenia, keď svalové napätie zvyšuje nároky na dych." },
      { name: "Basketbal", subtitle: "Individuálna streľba na kôš", desc: "Aktívna streľba spojená s okamžitým dobiehaním vlastných odrazov. Udrží srdce v aktivite bez vyčerpania z hry 3 na 3." },
      { name: "Vodné športy", subtitle: "Kanoistika / SUP", desc: "Rytmické zábery pádlom na pokojnej vode zapájajúce rotáciu trupu. Ideálne pre stabilitu a miernu aktiváciu dychu v prírode." },
      { name: "Chôdza", subtitle: "Snežnice po rovine", desc: "Pohyb v hlbokom snehu kladie odpor a zvyšuje náročnosť každého kroku. Umožňuje udržať plynulé tempo a prehĺbený dych." },
      { name: "Pálkovacie hry", subtitle: "Softball / Baseball", desc: "Počítajte iba minúty aktívneho behu, nadhadzovania alebo pálkovania. Väčšina času je statická, preto sčítajte iba momenty zrýchleného tepu." },
    ],
  },
  h3: {
    subtitle: "Kondičný schod",
    description: "Pohyb je už radosť. Tu začíname budovať skutočnú kondíciu.",
    activities: [
      { name: "Cvičenie", subtitle: "Aerobik / Zumba / Bodyform", desc: "Skupinové lekcie, ktoré vás vďaka hudbe a rytmu udržia v konštantnom kondičnom tempe. Najdostupnejšia forma organizovaného cvičenia." },
      { name: "Beh", subtitle: "Jogging / Pomalý beh", desc: "Základný kameň vytrvalosti s ľahkým došľapom. Užívajte si pohyb krajinou a dĺžku trasy navyšujte maximálne o 5–10 % týždenne." },
      { name: "Kruhový tréning", subtitle: "Intenzívne striedanie cvikov", desc: "Na rôzne svalové partie s minimálnymi pauzami. Udrží tep v optimálnej kondičnej zóne a efektívne buduje silu aj vytrvalosť." },
      { name: "Loptové hry", subtitle: "Futbal / Florbal / Basketbal", desc: "Rekreačné zápasy na menšom priestore s intervalovým charakterom. Krátke šprinty a zmeny smeru vás dostanú do zóny aktívneho zadýchania." },
      { name: "Tenis", subtitle: "Rekreačná úroveň", desc: "Aktívna hra na celom kurte so sústredením na pohyb nôh. Plynulé výmeny udržujú krvný obeh v neustálej aktivite." },
      { name: "Cyklistika", subtitle: "Spinning / Cyklotrenažér", desc: "Intenzívne šliapanie v kontrolovanom prostredí s hudbou či aplikáciami. Plné sústredenie na výkon a dych bez vonkajších vplyvov." },
      { name: "Plávanie", subtitle: "Kondičné plávanie", desc: "Súvislé plávanie niekoľkých bazénov v kuse so striedaním štýlov (prsia, znak). Minimalizácia páuz pri brehu pre udržanie tepu v kondičnej zóne." },
      { name: "Joga", subtitle: "Power joga", desc: "Dynamické striedanie pozícií v súlade s dychom, kladúce nároky na silu a stabilitu. Dych musí byť hlboký a vedome zrýchlený po celú dobu." },
      { name: "Cvičenie", subtitle: "TRX / Kettlebell", desc: "Funkčný tréning s odporom náradia. Technická precíznosť s krátkymi oddychovými intervalmi udrží srdce v aktivite a svaly pod napätím." },
      { name: "Chôdza", subtitle: "Rucking (chôdza so záťažovým batohom)", desc: "Svižná chôdza s batohom (5–15 % telesnej hmotnosti). Efektívne budovanie kondície šetriace kĺby, ale aktivujúce pľúca ako jogging." },
      { name: "Turistika", subtitle: "Horská turistika (strmá)", desc: "Rýchlejšia chôdza v členitom teréne s výrazným prevýšením. Práca proti gravitácii spoľahlivo zaistí vysokú tepovú frekvenciu." },
      { name: "Tanec", subtitle: "Latino / Intenzívne lekcie", desc: "Energické zostavy ako salsa, vyžadujúce rýchlu prácu nôh a trupu. Pohyb v rytme vás udrží v zóne kondičného zadýchania." },
      { name: "Schody", subtitle: "Intenzívny tréning", desc: "Cielené vybiehanie alebo veľmi rýchla chôdza do schodov (dva po dvoch). Najrýchlejšia cesta k preveriu vášho motora a sily nôh." },
      { name: "Bojové umenia", subtitle: "Judo / Karate – základný tréning", desc: "Nácvik techník v pohybe, tieňový boj alebo ľahký kondičný sparring. Výbušné pohyby spoľahlivo aktivujú kardiovaskulárny systém." },
      { name: "Lyžovanie", subtitle: "Skialpinizmus (ľahký terén)", desc: "Stúpanie do kopca na lyžiach, zapájajúce celé telo. Odpor snehu a práca s palicami zaistí zónu prehĺbeného kondičného dýchania." },
      { name: "Jazda", subtitle: "Skate / Longboard", desc: "Aktívny pohyb mestom s častým odrazom. Počítajte čas, keď sa aktívne odrážate alebo pracujete s ťažiskom, nie pasívne státie." },
      { name: "Tanec", subtitle: "Pole dance (kondičný)", desc: "Silovo-akrobatické cvičenie na tyči vyžadujúce spevnenie stredu tela. Počítajte čas nácviku prvkov, ktoré vás donútia k hlbokému dýchaniu." },
      { name: "Plávanie", subtitle: "Open water (prírodné plávanie)", desc: "Súvislý pohyb vo voľnej vode bez stien. Náročnejšie na orientáciu a udržanie teploty, čo robí z plávania vynikajúcu kondičnú aktivitu." },
    ],
  },
  h4: {
    subtitle: "Udržateľný stred",
    description: "Zlatý štandard H7. Tu sa láme chlieb pre celoživotné zdravie.",
    activities: [
      { name: "Cvičenie", subtitle: "Tabata / HIIT", desc: "Vysoko intenzívny intervalový tréning pre maximálne spaľovanie. Striedanie maximálneho úsilia a krátkeho oddychu udrží metabolizmus naštartovaný." },
      { name: "Beh", subtitle: "Systémový tréning", desc: "Striedanie dĺžky a intenzity (napr. fartlek). Učíte telo pracovať efektívne aj pri dlhšej záťaži, keď váš vnútorný diesel musí bežať naplno." },
      { name: "Tenis", subtitle: "Pravidelný tréning / Bedminton", desc: "Zameranie na dril úderov a hernú taktiku. Neustály pohyb v kombinácii s technikou robí z tréningu veľmi intenzívnu jednotku." },
      { name: "Cvičenie", subtitle: "CrossFit", desc: "Kombinácia gymnastiky, vzpierania a kardia. Sústreďujete sa na techniku a plynulosť v rámci tréningu dňa (WOD), čo preverí silu aj vytrvalosť." },
      { name: "Cyklistika", subtitle: "Horský bicykel (MTB)", desc: "Jazda v teréne vyžaduje silu aj techniku. Každý koreň a stúpanie sú prirodzeným intervalom pre nohy, trup aj paže." },
      { name: "Beh", subtitle: "Trail Running", desc: "Beh mimo spevnených ciest cez prekážky. Vyžaduje omnoho viac stability a sily než cestný beh. Výbehy v teréne budujú robustnú kondíciu." },
      { name: "Beh", subtitle: "Beh s kočíkom", desc: "Dlhšie trasy so záťažou výrazne zvyšujú náročnosť na stred tela a paže. Spojenie starostlivosti o dieťa s kvalitným vytrvalostným tréningom." },
      { name: "Veslovanie", subtitle: "Intenzívny tréning", desc: "Silný záber nohami a plynulé dýchanie. Komplexná záťaž pre celé telo budujúca svalovú vytrvalosť a kapacitu pľúc bez nárazov." },
      { name: "Squash", subtitle: "Výbušný pohyb so zmenami smeru", desc: "Intervalový charakter hry je skvelý pre spaľovanie tukov a posilnenie srdca. Vďaka tempu sa do H4 dostanete veľmi rýchlo." },
      { name: "Bojové športy", subtitle: "Box / Kickbox (kondičný)", desc: "Práca na vreci alebo s lapami v explozívnych sekvenciách. Buduje neuveriteľnú kondíciu hornej aj dolnej polovice tela." },
      { name: "Cyklistika", subtitle: "Gravel Biking", desc: "Rýchla jazda na pomedzí cesty a terénu. 35 minút ostrej jazdy v premenlivom teréne je ideálny H4 stimul pre nohy aj srdce." },
      { name: "Hokej", subtitle: "Ľadový hokej / Florbal (hobby)", desc: "Vysoké tempo a intenzívne striedanie simulujúce intervalový tréning. Pohyb na ľade či palubovke posúva výkonnostný strop." },
      { name: "Bežky", subtitle: "Kondičný tréning", desc: "Plné sústredenie na techniku odrazu a skĺzu. Práca paží a nôh v chlade je výzvou budujúcou železnú vytrvalosť." },
      { name: "Triatlon", subtitle: "Sprint triatlon (príprava)", desc: "Striedanie disciplín a nácvik prechodov. Komplexná príprava učí organizmus rýchlej adaptácii na rôzne typy záťaže." },
      { name: "Plávanie", subtitle: "Tréning s pomôckami", desc: "Použitie plutví alebo paciek na zvýšenie odporu. Intervalové úseky budujú špecifickú silu a nútia k efektívnejšiemu dýchaniu." },
      { name: "Beh", subtitle: "Orientačný beh", desc: "Beh v náročnom lese s čítaním mapy. Kombinácia fyzickej námahy v teréne a kognitívneho zaťaženia robí z behu jedinečný zážitok." },
      { name: "Frisbee", subtitle: "Ultimate Frisbee", desc: "Šport založený na šprinte a výskokoch. Vysoká intenzita vyžaduje koordináciu a schopnosť tela rýchlo regenerovať medzi akciami." },
      { name: "Vodné pólo", subtitle: "Ragby / Vodné pólo (tréning)", desc: "Extrémna fyzická odolnosť. Aj samotný dril vo vode alebo šprinty na ihrisku vás naučia pracovať v hlbokom kyslíkovom dlhu." },
      { name: "Gymnastika", subtitle: "Šerm / Moderná gymnastika", desc: "Intenzívny tréning vyžadujúci precíznosť a výbušnosť. Náročný na hlboký stabilizačný systém a srdcovú činnosť." },
      { name: "Zápas", subtitle: "Bojové športy (kondičné)", desc: "Tréning techník a pohybu na žinenke bez plného sparringu. Pretláčanie a práca s ťažiskom buduje funkčnú silu a vytrvalosť." },
    ],
  },
  h5: {
    subtitle: "Cesta k výkonu",
    description: "Tu už trénujete ako športovci.",
    activities: [
      { name: "Beh", subtitle: "Tréning na 15 km / Tempové behy", desc: "Ladenie formy na konkrétnu vzdialenosť. Striedate dlhé súvislé behy s tempovými úsekmi, ktoré učia telo hospodáriť s energiou." },
      { name: "Cyklistika", subtitle: "Kopcovitý terén", desc: "Dlhšie vyjazdenia s cieleným vyhľadávaním kopcov. Striedaním frekvencie šliapania (sila vs. točenie) rozvíjate pomalé aj rýchle svalové vlákna." },
      { name: "Plávanie", subtitle: "Závodný tréning / Intervaly", desc: "Špecifické série s krátkym oddychom. Tento typ záťaže buduje špecifickú vytrvalosť a učí držať techniku pod tlakom." },
      { name: "Cvičenie", subtitle: "CrossFit (výkonnostný)", desc: "Plné nasadenie v tréningoch WOD. Kombinácia silových a gymnastických prvkov vedie k výraznému nárastu absolútnej kondície." },
      { name: "Beh", subtitle: "Horský beh (intenzívny)", desc: "Beh v náročnom teréne s veľkým prevýšením. Buduje silné nohy a učí srdce pracovať v premenlivom rytme podľa sklonu." },
      { name: "Cyklistika", subtitle: "MTB XC / Trail", desc: "Pravidelný tréning techniky prejazdu. Striedanie výjazdov s tepom na maxime a technických zjazdov je komplexný športový výkon." },
      { name: "Bojové športy", subtitle: "Box / Thajský box (sparring)", desc: "Intenzívny tréning s partnerom. Extrémne náročné na dych a schopnosť pracovať v hlbokom kyslíkovom dlhu." },
      { name: "Triatlon", subtitle: "Sprint triatlon (závodné ambície)", desc: "Príprava na konkrétne preteky. Cieľom je pretekať, čo vyžaduje schopnosť rýchlo prepínať medzi rôznymi typmi svalovej práce." },
      { name: "Beh", subtitle: "Prekážkový beh (Spartan Sprint)", desc: "Kombinácia behu s nosením bremien a šplhom. Tréning buduje komplexnú postavu pre nepredvídateľné výzvy." },
      { name: "Lezenie", subtitle: "Výkonnostná úroveň", desc: "Lezenie ťažších ciest, kde bojujete s laktátom. Započítavajte čas strávený priamo v stene pod napätím." },
      { name: "Chôdza", subtitle: "Rucking / Dlhé túry", desc: "Chôdza s batohom (10–20 % hmotnosti) v ostrom tempe v kopcoch. Buduje železnú odolnosť tela bez veľkých nárazov." },
      { name: "Parkour", subtitle: "Pokročilá úroveň", desc: "Plynulý pohyb mestom s akrobatickými prvkami. Vyžaduje výbušnosť, koordináciu a silu stredu tela." },
      { name: "Korčuľovanie", subtitle: "Rýchlokorčuľovanie / Inline", desc: "Pravidelný tréning so zameraním na techniku odrazu a nízky postoj. Práca v konštantnom napätí stehien buduje špecifickú silu." },
      { name: "Vodný slalom", subtitle: "Tréning na divokej vode", desc: "Boj s prúdom vyžaduje extrémnu silu trupu a paží. Každý nájazd do bránky je explozívnym výkonom posúvajúcim kondíciu." },
      { name: "Atletika", subtitle: "Atletický viacboj / Dráha", desc: "Špecifický tréning na štadióne zameraný na rýchlostnú vytrvalosť a techniku. Nekompromisný k vášmu kardiovaskulárnemu systému." },
      { name: "Duatlon", subtitle: "Beh-Bicykel-Beh", desc: "Intenzívny tréning prechodov pre tých, ktorí neplávajú. Učí nohy pracovať v rôznych režimoch bez pauzy." },
      { name: "Lyžovanie", subtitle: "Skialpinizmus (športový)", desc: "Náročné výstupy s veľkým prevýšením. Ostré stúpanie budujúce obrovskú kapacitu pľúc a silu celého tela." },
      { name: "Trenažér", subtitle: "Pádlovanie / Kayak Erg", desc: "Intenzívne veslovanie alebo pádlovanie budujúce silu trupu a paží, nevyhnutnú pre triatlon aj funkčné zdravie." },
    ],
  },
  h6: {
    subtitle: "Brána k vytrvalosti",
    description: "Telo sa stáva vysoko ekonomickým strojom.",
    activities: [
      { name: "Beh", subtitle: "Polmaratónsky tréning", desc: "Trénujete ekonomiku pohybu a schopnosť udržať stabilitu v únave. Dlhé behy v teréne preveria vašu psychickú odolnosť." },
      { name: "Cyklistika", subtitle: "Objemové tréningy do 100 km", desc: "Budovanie základnej vytrvalosti v sedle. Učí telo efektívnejšie oxidovať tuky ako palivo a pripravuje šľachy na záťaž." },
      { name: "Turistika", subtitle: "Vysokohorská turistika", desc: "Náročné výstupy s batohom. Vertikálne metre budujú robustnú silu nôh a učia vás hospodáriť s dychom v náročnom teréne." },
      { name: "Plávanie", subtitle: "Open water (dlhé tréningy)", desc: "Tréning na otvorenej vode bez stien simuluje závodné podmienky a buduje psychickú stabilitu aj vytrvalostný stimul." },
      { name: "Cyklistika", subtitle: "MTB maratón (50–60 km)", desc: "Tréning na preteky v teréne kombinujúci vytrvalosť s technikou. Zvládanie výjazdov s tepom nadoraz aj technických zjazdov." },
      { name: "Bežky", subtitle: "Objemové tréningy", desc: "52 minút v bielej stope zapojí celé telo. Plynulý skĺz a rytmus rozvíjajú kapacitu pľúc a celkovú zdatnosť v zime." },
      { name: "Triatlon", subtitle: "Olympijský triatlon (tréning)", desc: "Kombinovanie disciplín (napr. plávanie + beh). Učíte sa prechody medzi rôznymi typmi svalovej práce (tzv. prechodové tréningy)." },
      { name: "Lyžovanie", subtitle: "Skialpinizmus (náročné trasy)", desc: "Výstupy vo voľnom teréne s veľkým prevýšením. Práca proti gravitácii a snehu je budovateľom vytrvalostného základu." },
      { name: "Beh", subtitle: "Spartan Super / Beast tréning", desc: "Kombinácia behu v teréne so silovými prvkami (nosenie bremien). Simulácia náročnosti dlhých prekážkových pretekov." },
      { name: "Veslovanie", subtitle: "Dlhé objemové tréningy", desc: "Rytmus a sila záberu po dlhší časový úsek. Vynikajúce pre trup a paže, buduje vytrvalosť bez dopadov na kĺby." },
      { name: "Adventure Race", subtitle: "Základná príprava", desc: "Kombinácia rôznych aktivít v jednom bloku (bicykel, beh, kanoistika). Učíte sa byť univerzálnym športovcom pre akékoľvek podmienky." },
      { name: "Cyklistika", subtitle: "Gravel grinding", desc: "Dlhé jazdy v miernom teréne (3+ hodiny). Budovanie sedacej vytrvalosti a tréning v zóne spaľovania tukov." },
      { name: "Plávanie", subtitle: "Sériový bazénový tréning", desc: "Napr. 5x 500 m s minimálnou pauzou. Vytrvalostný dril nevyhnutný pre posun k diaľkovému plávaniu a H7." },
      { name: "Kanoistika", subtitle: "Kondičná kanoistika / Kayak", desc: "Súvislé pádlovanie po dlhú dobu pre vytrvalosť hornej polovice tela, ktorú bežci často zanedbávajú." },
    ],
  },
  h7: {
    subtitle: "Život v pohybe",
    description: "Vrchol systému. Hodina denne ako automatický štandard a radosť.",
    activities: [
      { name: "Cyklistika", subtitle: "Závodná objemová vytrvalosť", desc: "60 minút v sedle je štandardom učiacim telo maximálnej ekonomike a efektívnemu spaľovaniu tukov pre dlhé výkony." },
      { name: "Beh", subtitle: "Maratónsky tréning", desc: "Pravidelné tréningy striedajúce intenzity. Vedomá práca s bežeckou formou a budovanie psychickej odolnosti pre extrémne vzdialenosti." },
      { name: "Cyklistika", subtitle: "MTB maratón (80–100 km)", desc: "Intenzívna jazda v náročnom teréne preverujúca techniku aj energetickú zdatnosť. Príprava na celodenné výzvy." },
      { name: "Loptové hry", subtitle: "Závodná príprava (Futbal / Basketbal)", desc: "Hra na vysokej úrovni vyžadujúca výbušnosť a rýchlu regeneráciu. Plnohodnotný športový výkon s dôrazom na taktiku." },
      { name: "Triatlon", subtitle: "Závodná výkonnosť", desc: "Ladenie formy vo všetkých disciplínach. Pilovanie prechodov, aby telo fungovalo ako jeden zohratý stroj pripravený na olympijskú vzdialenosť." },
      { name: "Plávanie", subtitle: "Diaľkové plávanie (tréning na 10 km)", desc: "Schopnosť udržať tempo a techniku po celú hodinu bez zastavenia. Buduje neuveriteľnú kapacitu pľúc." },
      { name: "Beh", subtitle: "Závodný beh do vrchu", desc: "Nekompromisný súboj s gravitáciou. Buduje extrémnu silu nôh a učí srdce pracovať na hranici maximálnych možností." },
      { name: "Hokej", subtitle: "Výkonnostný hokej", desc: "Rýchla a tvrdá hra vyžadujúca koncentráciu a silu. Intervalové striedanie v tempe udržuje kardiovaskulárny systém v absolútnej špičke." },
      { name: "Biatlon", subtitle: "Amatérska pravidelná príprava", desc: "Kombinácia vysokého tepu z behu a pokoja pri streľbe. Učí sebakontrole a ovládaniu dychu pod maximálnym tlakom." },
      { name: "Triatlon", subtitle: "Half Ironman príprava", desc: "Systematické skladanie hodín pre zvládnutie nárokov polovičného Ironmana. Ekonomické minimum, ktoré vás bezpečne dovedie do cieľa." },
      { name: "Cvičenie", subtitle: "Brick Training (prechody)", desc: "Bezprostredná kombinácia dvoch disciplín (napr. bicykel + beh) bez pauzy. Učíte telo zvládnuť zmenu typu záťaže." },
      { name: "Kombinácia", subtitle: "Ride & Run", desc: "Praktické spojenie dopravy a športu. Dôjsť na bicykli do terénu a tam absolvovať bežecký tréning pre rozvoj všestrannosti." },
      { name: "Posilňovanie", subtitle: "Silový dril pre vytrvalcov", desc: "Cielené zdvíhanie ťažších váh (drepy, mŕtve ťahy) pre prevenciu zranení a pevnosť šliach pri obrovskom ročnom objeme pohybu." },
    ],
  },
};

const BY_CODE: Record<"cs" | "en" | "sk", LevelActivityDetails> = {
  cs: CS_DETAILS,
  en: EN_DETAILS,
  sk: SK_DETAILS,
};

export function getLevelActivityDetails(code: "cs" | "en" | "sk"): LevelActivityDetails {
  return BY_CODE[code] ?? EN_DETAILS;
}

export function getLevelInfo(code: "cs" | "en" | "sk", level: number): LevelInfo | null {
  if (level < 1 || level > 7) return null;
  const key = ("h" + level) as LevelKey;
  return BY_CODE[code]?.[key] ?? EN_DETAILS[key] ?? null;
}

// Look up an activity by its English name anywhere in H1..H7 and return the
// matching localized detail (in the caller's locale). Used by the My Path
// H8+ tiles: those levels have no dedicated content, but many of the
// activity *names* (Running, Cycling, …) appear verbatim in lower levels.
// When they do, we surface the same detail sheet so the tile still opens.
//
// The details arrays are parallel across locales (same activity at same
// index in CS/EN/SK), so we match against EN_DETAILS and then read the
// same (level, index) slot from the caller's locale.
const LEVEL_KEYS: LevelKey[] = ["h1", "h2", "h3", "h4", "h5", "h6", "h7"];

export function findActivityDetailByEnglishName(
  code: "cs" | "en" | "sk",
  englishName: string,
): LevelActivityDetail | null {
  const needle = englishName.trim().toLowerCase();
  if (!needle) return null;
  for (const key of LEVEL_KEYS) {
    const enActivities = EN_DETAILS[key].activities;
    const idx = enActivities.findIndex(
      (a) => a.name.trim().toLowerCase() === needle,
    );
    if (idx === -1) continue;
    const localized = BY_CODE[code]?.[key]?.activities[idx];
    return localized ?? enActivities[idx];
  }
  return null;
}
